name: Adventure Club
favicon: null
layout_spectrum: 0.9470345864538103
typography_spectrum: 0.14705116371624172
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.28952642413787544
  lightness: 0.4447885318659246
  saturation: 0.5171971328090876
  rhythmicContrast: 0.8584952782839537
purpose: []
